# Generated by Django 2.2.10 on 2021-07-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_feedback_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
