# Generated by Django 2.2.10 on 2021-07-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='college_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name '),
        ),
    ]
